---
- name: Start Cassandra node
  ansible.builtin.service:
    name: cassandra
    state: started

- name: 'Wait for Cassandra process to be up and running on {{ ansible_default_ipv4.address }}'
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: 9042
    delay: 1

- pause:
    prompt: "Pause for 30s after starting this node"
    seconds: 30
